export const constant = {
  REFRESH_CUSTOMER_ADDRESSES: "REFRESH_CUSTOMER_ADDRESSES",
  REFRESH_CART: "REFRESH_CART",
  REFRESH_CART_ITEMS_QTY: "REFRESH_CART_ITEMS_QTY",
  REFRESH_SHIPPING_METHODS: "REFRESH_SHIPPING_METHODS",
  REFRESH_CART_ON_SHIPPING_METHODS_CHANGE: "REFRESH_CART_ON_SHIPPING_METHODS_CHANGE",
  REFRESH_CART_ON_PAYMENT_METHODS_CHANGE: "REFRESH_CART_ON_PAYMENT_METHODS_CHANGE",
  REFRESH_CART_ON_EXTRAFEE_CHANGE: "REFRESH_CART_ON_EXTRAFEE_CHANGE",
  UPDATE_CUSTOMER_DEFAULT_ADDRESS: "UPDATE_CUSTOMER_DEFAULT_ADDRESS",
  UPDATE_CART_EMAIL: "UPDATE_CART_EMAIL",
  SET_DELIVERY_METHOD: "SET_DELIVERY_METHOD",
  APPLY_REWARD_POINTS: "APPLY_REWARD_POINTS",
  APPLY_STORE_CREDIT: "APPLY_STORE_CREDIT",
  REMOVE_REWARD_POINTS: "REMOVE_REWARD_POINTS",
  REMOVE_STORE_CREDIT: "REMOVE STORE CREDIT"
};